services:
  mariadb:
    image: mariadb:10.9
    environment:
      - MARIADB_DATABASE=n8n
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_MYSQL_LOCALHOST_USER=true
    ports:
      - 3306:3306
    tmpfs:
      - /var/lib/mysql

  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=https://n8n-kn80.onrender.com
      - N8N_PORT=443
      - N8N_PROTOCOL=https
      - WEBHOOK_TUNNEL_URL=https://n8n-kn80.onrender.com
      - N8N_CONFIG_FILES=/config.json
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./config.json:/config.json
